/*
 * Copyright: Kitakod Ventures 2026
 * This file and its contents are licensed under the AGPLv3 License.
 * Please see the included NOTICE for copyright information and
 * LICENSE-AGPL for a copy of the license.
 */
//! Shared LLM client module.
//!
//! Provides a provider-agnostic interface for calling LLMs (OpenAI, Anthropic,
//! Ollama, and OpenAI-compatible custom endpoints). Used by the generator and
//! other internal components that need to call LLMs without duplicating the
//! per-provider HTTP logic from the agent node.

//! NOTE: `src/nodes/agent.rs` contains a separate, private LLM client with
//! additional features (ZeptoClaw integration, JSON schema validation,
//! response_format handling). This module is intentionally separate — it
//! provides a simpler interface for the generator and other internal tools.
//! If a provider changes its API shape, both modules need updating.

use reqwest::header::HeaderValue;
use reqwest::Client;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::time::Duration;
use tokio::sync::mpsc;
use tracing::{debug, warn};

use crate::error::{Error, Result};

// ---------------------------------------------------------------------------
// Provider enum
// ---------------------------------------------------------------------------

/// LLM provider selection.
#[derive(Debug, Deserialize, Serialize, Default, Clone, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum LlmProvider {
    /// OpenAI API (default). Also used for OpenAI-compatible endpoints.
    #[default]
    Openai,
    /// Anthropic Claude API.
    Anthropic,
    /// Ollama local model server.
    Ollama,
    /// Custom OpenAI-compatible endpoint (same request format as Openai).
    Custom,
}

// ---------------------------------------------------------------------------
// Config / request types
// ---------------------------------------------------------------------------

/// Configuration for an LLM call.
#[derive(Deserialize, Serialize, Clone)]
pub struct LlmConfig {
    /// LLM provider to use. Defaults to OpenAI.
    #[serde(default)]
    pub provider: LlmProvider,

    /// Model name (e.g. "gpt-4o", "claude-3-haiku-20240307", "llama3").
    /// If omitted, a provider-specific default is used.
    #[serde(default)]
    pub model: Option<String>,

    /// API key. Required for OpenAI, Anthropic, and Custom providers;
    /// not used for Ollama.
    #[serde(default, skip_serializing)]
    pub api_key: Option<String>,

    /// Override the default endpoint URL for the selected provider.
    #[serde(default)]
    pub endpoint: Option<String>,

    /// Sampling temperature (0.0–2.0). Provider-default used when absent.
    #[serde(default)]
    pub temperature: Option<f32>,

    /// Maximum tokens to generate. Provider-default used when absent.
    #[serde(default)]
    pub max_tokens: Option<u32>,

    /// HTTP timeout in seconds. Defaults to 60.
    #[serde(default = "default_timeout_seconds")]
    pub timeout_seconds: u64,
}

impl std::fmt::Debug for LlmConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("LlmConfig")
            .field("provider", &self.provider)
            .field("model", &self.model)
            .field("api_key", &self.api_key.as_ref().map(|_| "[REDACTED]"))
            .field("endpoint", &self.endpoint)
            .field("temperature", &self.temperature)
            .field("max_tokens", &self.max_tokens)
            .field("timeout_seconds", &self.timeout_seconds)
            .finish()
    }
}

fn default_timeout_seconds() -> u64 {
    60
}

impl Default for LlmConfig {
    fn default() -> Self {
        Self {
            provider: LlmProvider::Openai,
            model: None,
            api_key: None,
            endpoint: None,
            temperature: None,
            max_tokens: None,
            timeout_seconds: 60,
        }
    }
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/// Parsed response from an LLM call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmResponse {
    /// The text content generated by the model.
    pub content: String,
    /// The model identifier returned by the provider.
    pub model: String,
    /// Token usage reported by the provider (if available).
    pub usage: Option<LlmUsage>,
}

/// Token usage information from an LLM response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmUsage {
    /// Number of tokens in the prompt / input.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_tokens: Option<u64>,
    /// Number of tokens in the completion / output.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completion_tokens: Option<u64>,
}

// ---------------------------------------------------------------------------
// Streaming types
// ---------------------------------------------------------------------------

/// Events emitted by a streaming LLM response.
#[derive(Debug, Clone)]
pub enum StreamEvent {
    /// A chunk of assistant text.
    TextDelta(String),
    /// Tool call start (name and identifier).
    ToolCallStart { id: String, name: String },
    /// Tool call argument chunk.
    ToolCallDelta { id: String, arguments: String },
    /// Token usage data from the final chunk.
    Usage(LlmUsage),
    /// Stream completed.
    Done,
}

// ---------------------------------------------------------------------------
// Default endpoint helpers
// ---------------------------------------------------------------------------

fn default_openai_endpoint() -> String {
    "https://api.openai.com/v1/chat/completions".to_string()
}

fn default_anthropic_endpoint() -> String {
    "https://api.anthropic.com/v1/messages".to_string()
}

fn default_ollama_endpoint() -> String {
    "http://localhost:11434/api/chat".to_string()
}

fn resolve_endpoint(config: &LlmConfig) -> String {
    if let Some(ep) = &config.endpoint {
        return ep.clone();
    }
    match config.provider {
        LlmProvider::Openai | LlmProvider::Custom => default_openai_endpoint(),
        LlmProvider::Anthropic => default_anthropic_endpoint(),
        LlmProvider::Ollama => default_ollama_endpoint(),
    }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Creates an HTTP client with a 10-second connection timeout. Per-request
/// timeouts are applied by call_llm using LlmConfig::timeout_seconds.
pub fn create_llm_client() -> Client {
    const CONNECT_TIMEOUT_SECS: u64 = 10;

    Client::builder()
        .connect_timeout(Duration::from_secs(CONNECT_TIMEOUT_SECS))
        .build()
        .unwrap_or_else(|e| {
            warn!(
                "Failed to build LLM HTTP client with timeout defaults: {}",
                e
            );
            Client::new()
        })
}

/// Dispatch an LLM chat completion call to the configured provider.
///
/// # Arguments
/// - `client` — a `reqwest::Client` (e.g. from [`create_llm_client`])
/// - `config` — provider/model/credential configuration
/// - `system` — optional system prompt
/// - `user` — user message
///
/// # Errors
/// Returns `Error::Node` for provider-level issues (missing API key, unexpected
/// response shape) and propagates `Error::Http` / `Error::Json` from the
/// network and JSON layers.
pub async fn call_llm(
    client: &Client,
    config: &LlmConfig,
    system: Option<&str>,
    user: &str,
) -> Result<LlmResponse> {
    match config.provider {
        LlmProvider::Openai | LlmProvider::Custom => {
            call_openai(client, config, system, user).await
        }
        LlmProvider::Anthropic => call_anthropic(client, config, system, user).await,
        LlmProvider::Ollama => call_ollama(client, config, system, user).await,
    }
}

/// Call the LLM with streaming, returning a channel of parsed stream events.
///
/// `messages` should contain OpenAI-style role/content objects.
pub async fn call_llm_streaming(
    client: &Client,
    config: &LlmConfig,
    system: Option<&str>,
    messages: &[serde_json::Value],
    tools: Option<&[serde_json::Value]>,
) -> Result<mpsc::Receiver<StreamEvent>> {
    let (tx, rx) = mpsc::channel(256);

    match config.provider {
        LlmProvider::Openai | LlmProvider::Custom => {
            let response =
                build_openai_streaming_request(client, config, system, messages, tools).await?;
            tokio::spawn(async move {
                stream_sse_lines(response, tx, parse_openai_sse_line).await;
            });
        }
        LlmProvider::Anthropic => {
            let response =
                build_anthropic_streaming_request(client, config, system, messages, tools).await?;
            tokio::spawn(async move {
                stream_sse_lines(response, tx, parse_anthropic_sse_line).await;
            });
        }
        LlmProvider::Ollama => {
            let response = build_ollama_streaming_request(client, config, system, messages).await?;
            tokio::spawn(async move {
                stream_ndjson_lines(response, tx).await;
            });
        }
    }

    Ok(rx)
}

// ---------------------------------------------------------------------------
// SSE/NDJSON parsers
// ---------------------------------------------------------------------------

/// Parse one OpenAI-compatible SSE line into a stream event.
pub fn parse_openai_sse_line(line: &str) -> Option<StreamEvent> {
    let data = line.strip_prefix("data: ")?;
    if data == "[DONE]" {
        return Some(StreamEvent::Done);
    }
    let v: serde_json::Value = serde_json::from_str(data).ok()?;

    // Check for usage in final chunk FIRST (before choices processing)
    if let Some(usage) = v.get("usage") {
        if !usage.is_null() {
            return Some(StreamEvent::Usage(LlmUsage {
                prompt_tokens: usage.get("prompt_tokens").and_then(|v| v.as_u64()),
                completion_tokens: usage.get("completion_tokens").and_then(|v| v.as_u64()),
            }));
        }
    }

    let delta = &v["choices"][0]["delta"];

    if let Some(tool_calls) = delta["tool_calls"].as_array() {
        if let Some(tc) = tool_calls.first() {
            if let Some(name) = tc["function"]["name"].as_str() {
                let id = tc["id"].as_str().unwrap_or("").to_string();
                return Some(StreamEvent::ToolCallStart {
                    id,
                    name: name.to_string(),
                });
            }
            if let Some(arguments) = tc["function"]["arguments"].as_str() {
                if !arguments.is_empty() {
                    let id = tc["id"].as_str().unwrap_or("").to_string();
                    return Some(StreamEvent::ToolCallDelta {
                        id,
                        arguments: arguments.to_string(),
                    });
                }
            }
        }
    }

    if let Some(content) = delta["content"].as_str() {
        if !content.is_empty() {
            return Some(StreamEvent::TextDelta(content.to_string()));
        }
    }

    None
}

/// Parse one Anthropic SSE line into a stream event.
pub fn parse_anthropic_sse_line(line: &str) -> Option<StreamEvent> {
    let data = line.strip_prefix("data: ")?;
    let v: serde_json::Value = serde_json::from_str(data).ok()?;

    match v["type"].as_str()? {
        "content_block_start" => {
            let block = &v["content_block"];
            if block["type"].as_str()? == "tool_use" {
                return Some(StreamEvent::ToolCallStart {
                    id: block["id"].as_str().unwrap_or("").to_string(),
                    name: block["name"].as_str().unwrap_or("").to_string(),
                });
            }
            None
        }
        "content_block_delta" => {
            let delta = &v["delta"];
            match delta["type"].as_str()? {
                "text_delta" => {
                    let text = delta["text"].as_str()?;
                    if text.is_empty() {
                        None
                    } else {
                        Some(StreamEvent::TextDelta(text.to_string()))
                    }
                }
                "input_json_delta" => {
                    let partial_json = delta["partial_json"].as_str()?;
                    Some(StreamEvent::ToolCallDelta {
                        id: String::new(),
                        arguments: partial_json.to_string(),
                    })
                }
                _ => None,
            }
        }
        "message_delta" => v.get("usage").map(|usage| {
            StreamEvent::Usage(LlmUsage {
                prompt_tokens: usage.get("input_tokens").and_then(|t| t.as_u64()),
                completion_tokens: usage.get("output_tokens").and_then(|t| t.as_u64()),
            })
        }),
        "message_stop" => Some(StreamEvent::Done),
        _ => None,
    }
}

/// Parse one Ollama NDJSON line into a stream event.
pub fn parse_ollama_ndjson_line(line: &str) -> Option<StreamEvent> {
    let v: serde_json::Value = serde_json::from_str(line).ok()?;
    if v["done"].as_bool() == Some(true) {
        return Some(StreamEvent::Done);
    }
    let content = v["message"]["content"].as_str()?;
    if content.is_empty() {
        None
    } else {
        Some(StreamEvent::TextDelta(content.to_string()))
    }
}

// ---------------------------------------------------------------------------
// Provider-specific implementations
// ---------------------------------------------------------------------------

async fn call_openai(
    client: &Client,
    config: &LlmConfig,
    system: Option<&str>,
    user: &str,
) -> Result<LlmResponse> {
    let api_key = config.api_key.as_deref().ok_or_else(|| {
        Error::Node("OpenAI API key is required. Set `api_key` in LlmConfig.".to_string())
    })?;

    let url = resolve_endpoint(config);
    let model = config.model.clone().unwrap_or_else(|| "gpt-4o".to_string());

    debug!(provider = "openai", model = %model, url = %url, "Sending LLM request");

    let mut headers = reqwest::header::HeaderMap::new();
    headers.insert(
        reqwest::header::AUTHORIZATION,
        format!("Bearer {}", api_key)
            .parse()
            .map_err(|_| Error::Node("Invalid OpenAI API key format".to_string()))?,
    );
    headers.insert(
        reqwest::header::CONTENT_TYPE,
        HeaderValue::from_static("application/json"),
    );

    let mut messages = Vec::new();
    if let Some(sys) = system {
        messages.push(json!({"role": "system", "content": sys}));
    }
    messages.push(json!({"role": "user", "content": user}));

    let mut body = json!({
        "model": model,
        "messages": messages,
    });

    if let Some(temp) = config.temperature {
        body["temperature"] = json!(temp);
    }
    if let Some(max_tok) = config.max_tokens {
        body["max_tokens"] = json!(max_tok);
    }

    let response = client
        .post(&url)
        .headers(headers)
        .json(&body)
        .timeout(Duration::from_secs(config.timeout_seconds))
        .send()
        .await?;

    let status = response.status();
    debug!(provider = "openai", status = %status, "Received LLM response");
    let json: serde_json::Value = response.json().await?;

    if !status.is_success() {
        let msg = json["error"]["message"]
            .as_str()
            .unwrap_or("Unknown OpenAI error");
        return Err(Error::Node(format!(
            "OpenAI API error ({}): {}",
            status, msg
        )));
    }

    let content = json["choices"][0]["message"]["content"]
        .as_str()
        .ok_or_else(|| Error::Node("Could not extract content from OpenAI response".to_string()))?
        .to_string();

    let returned_model = json["model"].as_str().unwrap_or(&model).to_string();

    let usage = if json.get("usage").is_some() {
        Some(LlmUsage {
            prompt_tokens: json["usage"]["prompt_tokens"].as_u64(),
            completion_tokens: json["usage"]["completion_tokens"].as_u64(),
        })
    } else {
        None
    };

    Ok(LlmResponse {
        content,
        model: returned_model,
        usage,
    })
}

async fn build_openai_streaming_request(
    client: &Client,
    config: &LlmConfig,
    system: Option<&str>,
    messages: &[serde_json::Value],
    tools: Option<&[serde_json::Value]>,
) -> Result<reqwest::Response> {
    let api_key = config.api_key.as_deref().ok_or_else(|| {
        Error::Node("OpenAI API key is required. Set `api_key` in LlmConfig.".to_string())
    })?;
    let url = resolve_endpoint(config);
    let model = config.model.clone().unwrap_or_else(|| "gpt-4o".to_string());

    let mut all_messages = Vec::new();
    if let Some(sys) = system {
        all_messages.push(json!({"role": "system", "content": sys}));
    }
    all_messages.extend_from_slice(messages);

    let mut body = json!({
        "model": model,
        "messages": all_messages,
        "stream": true,
        "stream_options": {"include_usage": true},
    });
    if let Some(temp) = config.temperature {
        body["temperature"] = json!(temp);
    }
    if let Some(max_tok) = config.max_tokens {
        body["max_tokens"] = json!(max_tok);
    }
    if let Some(tool_defs) = tools {
        body["tools"] = json!(tool_defs);
    }

    let response = client
        .post(&url)
        .header("Authorization", format!("Bearer {}", api_key))
        .header("Content-Type", "application/json")
        .json(&body)
        .timeout(Duration::from_secs(config.timeout_seconds))
        .send()
        .await
        .map_err(Error::Http)?;

    if !response.status().is_success() {
        let status = response.status();
        let text = response.text().await.unwrap_or_default();
        return Err(Error::Node(format!(
            "OpenAI API error {}: {}",
            status, text
        )));
    }

    Ok(response)
}

async fn call_anthropic(
    client: &Client,
    config: &LlmConfig,
    system: Option<&str>,
    user: &str,
) -> Result<LlmResponse> {
    let api_key = config.api_key.as_deref().ok_or_else(|| {
        Error::Node("Anthropic API key is required. Set `api_key` in LlmConfig.".to_string())
    })?;

    let url = resolve_endpoint(config);
    let model = config
        .model
        .clone()
        .unwrap_or_else(|| "claude-3-haiku-20240307".to_string());

    debug!(provider = "anthropic", model = %model, url = %url, "Sending LLM request");

    let mut headers = reqwest::header::HeaderMap::new();
    headers.insert(
        "x-api-key",
        api_key
            .parse()
            .map_err(|_| Error::Node("Invalid Anthropic API key format".to_string()))?,
    );
    headers.insert("anthropic-version", HeaderValue::from_static("2023-06-01"));
    headers.insert(
        reqwest::header::CONTENT_TYPE,
        HeaderValue::from_static("application/json"),
    );

    let max_tokens = config.max_tokens.unwrap_or(4096);

    let mut body = json!({
        "model": model,
        "max_tokens": max_tokens,
        "messages": [
            {"role": "user", "content": user}
        ],
    });

    if let Some(sys) = system {
        body["system"] = json!(sys);
    }
    if let Some(temp) = config.temperature {
        body["temperature"] = json!(temp);
    }

    let response = client
        .post(&url)
        .headers(headers)
        .json(&body)
        .timeout(Duration::from_secs(config.timeout_seconds))
        .send()
        .await?;

    let status = response.status();
    debug!(provider = "anthropic", status = %status, "Received LLM response");
    let json: serde_json::Value = response.json().await?;

    if !status.is_success() {
        let msg = json["error"]["message"]
            .as_str()
            .unwrap_or("Unknown Anthropic error");
        return Err(Error::Node(format!(
            "Anthropic API error ({}): {}",
            status, msg
        )));
    }

    let content = json["content"][0]["text"]
        .as_str()
        .ok_or_else(|| {
            Error::Node("Could not extract content from Anthropic response".to_string())
        })?
        .to_string();

    let returned_model = json["model"].as_str().unwrap_or(&model).to_string();

    let usage = if json.get("usage").is_some() {
        Some(LlmUsage {
            prompt_tokens: json["usage"]["input_tokens"].as_u64(),
            completion_tokens: json["usage"]["output_tokens"].as_u64(),
        })
    } else {
        None
    };

    Ok(LlmResponse {
        content,
        model: returned_model,
        usage,
    })
}

async fn build_anthropic_streaming_request(
    client: &Client,
    config: &LlmConfig,
    system: Option<&str>,
    messages: &[serde_json::Value],
    tools: Option<&[serde_json::Value]>,
) -> Result<reqwest::Response> {
    let api_key = config.api_key.as_deref().ok_or_else(|| {
        Error::Node("Anthropic API key is required. Set `api_key` in LlmConfig.".to_string())
    })?;
    let url = resolve_endpoint(config);
    let model = config
        .model
        .clone()
        .unwrap_or_else(|| "claude-sonnet-4-20250514".to_string());
    let max_tokens = config.max_tokens.unwrap_or(4096);

    let mut body = json!({
        "model": model,
        "max_tokens": max_tokens,
        "messages": messages,
        "stream": true,
    });
    if let Some(sys) = system {
        body["system"] = json!(sys);
    }
    if let Some(temp) = config.temperature {
        body["temperature"] = json!(temp);
    }
    if let Some(tool_defs) = tools {
        body["tools"] = json!(tool_defs);
    }

    let response = client
        .post(&url)
        .header("x-api-key", api_key)
        .header("anthropic-version", "2023-06-01")
        .header("Content-Type", "application/json")
        .json(&body)
        .timeout(Duration::from_secs(config.timeout_seconds))
        .send()
        .await
        .map_err(Error::Http)?;

    if !response.status().is_success() {
        let status = response.status();
        let text = response.text().await.unwrap_or_default();
        return Err(Error::Node(format!(
            "Anthropic API error {}: {}",
            status, text
        )));
    }

    Ok(response)
}

async fn call_ollama(
    client: &Client,
    config: &LlmConfig,
    system: Option<&str>,
    user: &str,
) -> Result<LlmResponse> {
    let url = resolve_endpoint(config);

    let model = config.model.clone().unwrap_or_else(|| "llama3".to_string());

    debug!(provider = "ollama", model = %model, url = %url, "Sending LLM request");

    let mut messages = Vec::new();
    if let Some(sys) = system {
        messages.push(json!({"role": "system", "content": sys}));
    }
    messages.push(json!({"role": "user", "content": user}));

    let mut body = json!({
        "model": model,
        "messages": messages,
        "stream": false,
    });

    if let Some(temp) = config.temperature {
        body["options"] = json!({"temperature": temp});
    }

    let response = client
        .post(&url)
        .json(&body)
        .timeout(Duration::from_secs(config.timeout_seconds))
        .send()
        .await?;

    let status = response.status();
    debug!(provider = "ollama", status = %status, "Received LLM response");
    let json: serde_json::Value = response.json().await?;

    if !status.is_success() {
        let msg = json["error"].as_str().unwrap_or("Unknown Ollama error");
        return Err(Error::Node(format!(
            "Ollama API error ({}): {}",
            status, msg
        )));
    }

    let content = json["message"]["content"]
        .as_str()
        .ok_or_else(|| Error::Node("Could not extract content from Ollama response".to_string()))?
        .to_string();

    // Ollama echoes the model name in the response; fall back to the config value.
    let returned_model = json["model"].as_str().unwrap_or(&model).to_string();

    let usage = if json.get("prompt_eval_count").is_some() {
        Some(LlmUsage {
            prompt_tokens: json["prompt_eval_count"].as_u64(),
            completion_tokens: json["eval_count"].as_u64(),
        })
    } else {
        None
    };

    Ok(LlmResponse {
        content,
        model: returned_model,
        usage,
    })
}

async fn build_ollama_streaming_request(
    client: &Client,
    config: &LlmConfig,
    system: Option<&str>,
    messages: &[serde_json::Value],
) -> Result<reqwest::Response> {
    let url = resolve_endpoint(config);
    let model = config.model.clone().unwrap_or_else(|| "llama3".to_string());

    let mut all_messages = Vec::new();
    if let Some(sys) = system {
        all_messages.push(json!({"role": "system", "content": sys}));
    }
    all_messages.extend_from_slice(messages);

    let mut body = json!({
        "model": model,
        "messages": all_messages,
        "stream": true,
    });
    if let Some(temp) = config.temperature {
        body["options"] = json!({"temperature": temp});
    }

    let response = client
        .post(&url)
        .json(&body)
        .timeout(Duration::from_secs(config.timeout_seconds))
        .send()
        .await
        .map_err(Error::Http)?;

    Ok(response)
}

async fn stream_sse_lines(
    mut response: reqwest::Response,
    tx: mpsc::Sender<StreamEvent>,
    parser: fn(&str) -> Option<StreamEvent>,
) {
    let mut buffer = String::new();

    while let Ok(Some(chunk)) = response.chunk().await {
        buffer.push_str(&String::from_utf8_lossy(&chunk));

        while let Some(newline_pos) = buffer.find('\n') {
            let line = buffer[..newline_pos].trim().to_string();
            buffer = buffer[newline_pos + 1..].to_string();

            if line.is_empty() || line.starts_with(':') {
                continue;
            }

            if let Some(event) = parser(&line) {
                let is_done = matches!(event, StreamEvent::Done);
                if tx.send(event).await.is_err() {
                    return;
                }
                if is_done {
                    return;
                }
            }
        }
    }

    let _ = tx.send(StreamEvent::Done).await;
}

async fn stream_ndjson_lines(mut response: reqwest::Response, tx: mpsc::Sender<StreamEvent>) {
    let mut buffer = String::new();

    while let Ok(Some(chunk)) = response.chunk().await {
        buffer.push_str(&String::from_utf8_lossy(&chunk));

        while let Some(newline_pos) = buffer.find('\n') {
            let line = buffer[..newline_pos].trim().to_string();
            buffer = buffer[newline_pos + 1..].to_string();

            if line.is_empty() {
                continue;
            }

            if let Some(event) = parse_ollama_ndjson_line(&line) {
                let is_done = matches!(event, StreamEvent::Done);
                if is_done {
                    // Extract usage from the raw line before sending Done
                    if let Ok(json) = serde_json::from_str::<serde_json::Value>(&line) {
                        let prompt_tokens = json.get("prompt_eval_count").and_then(|v| v.as_u64());
                        let completion_tokens = json.get("eval_count").and_then(|v| v.as_u64());
                        if prompt_tokens.is_some() || completion_tokens.is_some() {
                            let _ = tx
                                .send(StreamEvent::Usage(LlmUsage {
                                    prompt_tokens,
                                    completion_tokens,
                                }))
                                .await;
                        }
                    }
                }
                if tx.send(event).await.is_err() {
                    return;
                }
                if is_done {
                    return;
                }
            }
        }
    }

    let _ = tx.send(StreamEvent::Done).await;
}
