//! Shared LLM client module.
//!
//! Provides a provider-agnostic interface for calling LLMs (OpenAI, Anthropic,
//! Ollama, and OpenAI-compatible custom endpoints). Used by the generator and
//! other internal components that need to call LLMs without duplicating the
//! per-provider HTTP logic from the agent node.

//! NOTE: `src/nodes/agent.rs` contains a separate, private LLM client with
//! additional features (ZeptoClaw integration, JSON schema validation,
//! response_format handling). This module is intentionally separate — it
//! provides a simpler interface for the generator and other internal tools.
//! If a provider changes its API shape, both modules need updating.

use reqwest::header::HeaderValue;
use reqwest::Client;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::time::Duration;
use tracing::{debug, warn};

use crate::error::{Error, Result};

// ---------------------------------------------------------------------------
// Provider enum
// ---------------------------------------------------------------------------

/// LLM provider selection.
#[derive(Debug, Deserialize, Serialize, Default, Clone, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum LlmProvider {
    /// OpenAI API (default). Also used for OpenAI-compatible endpoints.
    #[default]
    Openai,
    /// Anthropic Claude API.
    Anthropic,
    /// Ollama local model server.
    Ollama,
    /// Custom OpenAI-compatible endpoint (same request format as Openai).
    Custom,
}

// ---------------------------------------------------------------------------
// Config / request types
// ---------------------------------------------------------------------------

/// Configuration for an LLM call.
#[derive(Deserialize, Serialize, Clone)]
pub struct LlmConfig {
    /// LLM provider to use. Defaults to OpenAI.
    #[serde(default)]
    pub provider: LlmProvider,

    /// Model name (e.g. "gpt-4o", "claude-3-haiku-20240307", "llama3").
    /// If omitted, a provider-specific default is used.
    #[serde(default)]
    pub model: Option<String>,

    /// API key. Required for OpenAI, Anthropic, and Custom providers;
    /// not used for Ollama.
    #[serde(default, skip_serializing)]
    pub api_key: Option<String>,

    /// Override the default endpoint URL for the selected provider.
    #[serde(default)]
    pub endpoint: Option<String>,

    /// Sampling temperature (0.0–2.0). Provider-default used when absent.
    #[serde(default)]
    pub temperature: Option<f32>,

    /// Maximum tokens to generate. Provider-default used when absent.
    #[serde(default)]
    pub max_tokens: Option<u32>,

    /// HTTP timeout in seconds. Defaults to 60.
    #[serde(default = "default_timeout_seconds")]
    pub timeout_seconds: u64,
}

impl std::fmt::Debug for LlmConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("LlmConfig")
            .field("provider", &self.provider)
            .field("model", &self.model)
            .field("api_key", &self.api_key.as_ref().map(|_| "[REDACTED]"))
            .field("endpoint", &self.endpoint)
            .field("temperature", &self.temperature)
            .field("max_tokens", &self.max_tokens)
            .field("timeout_seconds", &self.timeout_seconds)
            .finish()
    }
}

fn default_timeout_seconds() -> u64 {
    60
}

impl Default for LlmConfig {
    fn default() -> Self {
        Self {
            provider: LlmProvider::Openai,
            model: None,
            api_key: None,
            endpoint: None,
            temperature: None,
            max_tokens: None,
            timeout_seconds: 60,
        }
    }
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/// Parsed response from an LLM call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmResponse {
    /// The text content generated by the model.
    pub content: String,
    /// The model identifier returned by the provider.
    pub model: String,
    /// Token usage reported by the provider (if available).
    pub usage: Option<LlmUsage>,
}

/// Token usage information from an LLM response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmUsage {
    /// Number of tokens in the prompt / input.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_tokens: Option<u64>,
    /// Number of tokens in the completion / output.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completion_tokens: Option<u64>,
}

// ---------------------------------------------------------------------------
// Default endpoint helpers
// ---------------------------------------------------------------------------

fn default_openai_endpoint() -> String {
    "https://api.openai.com/v1/chat/completions".to_string()
}

fn default_anthropic_endpoint() -> String {
    "https://api.anthropic.com/v1/messages".to_string()
}

fn default_ollama_endpoint() -> String {
    "http://localhost:11434/api/chat".to_string()
}

fn resolve_endpoint(config: &LlmConfig) -> String {
    if let Some(ep) = &config.endpoint {
        return ep.clone();
    }
    match config.provider {
        LlmProvider::Openai | LlmProvider::Custom => default_openai_endpoint(),
        LlmProvider::Anthropic => default_anthropic_endpoint(),
        LlmProvider::Ollama => default_ollama_endpoint(),
    }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Creates an HTTP client with a 10-second connection timeout. Per-request
/// timeouts are applied by call_llm using LlmConfig::timeout_seconds.
pub fn create_llm_client() -> Client {
    const CONNECT_TIMEOUT_SECS: u64 = 10;

    Client::builder()
        .connect_timeout(Duration::from_secs(CONNECT_TIMEOUT_SECS))
        .build()
        .unwrap_or_else(|e| {
            warn!("Failed to build LLM HTTP client with timeout defaults: {}", e);
            Client::new()
        })
}

/// Dispatch an LLM chat completion call to the configured provider.
///
/// # Arguments
/// - `client` — a `reqwest::Client` (e.g. from [`create_llm_client`])
/// - `config` — provider/model/credential configuration
/// - `system` — optional system prompt
/// - `user` — user message
///
/// # Errors
/// Returns `Error::Node` for provider-level issues (missing API key, unexpected
/// response shape) and propagates `Error::Http` / `Error::Json` from the
/// network and JSON layers.
pub async fn call_llm(
    client: &Client,
    config: &LlmConfig,
    system: Option<&str>,
    user: &str,
) -> Result<LlmResponse> {
    match config.provider {
        LlmProvider::Openai | LlmProvider::Custom => call_openai(client, config, system, user).await,
        LlmProvider::Anthropic => call_anthropic(client, config, system, user).await,
        LlmProvider::Ollama => call_ollama(client, config, system, user).await,
    }
}

// ---------------------------------------------------------------------------
// Provider-specific implementations
// ---------------------------------------------------------------------------

async fn call_openai(
    client: &Client,
    config: &LlmConfig,
    system: Option<&str>,
    user: &str,
) -> Result<LlmResponse> {
    let api_key = config.api_key.as_deref().ok_or_else(|| {
        Error::Node("OpenAI API key is required. Set `api_key` in LlmConfig.".to_string())
    })?;

    let url = resolve_endpoint(config);
    let model = config
        .model
        .clone()
        .unwrap_or_else(|| "gpt-4o".to_string());

    debug!(provider = "openai", model = %model, url = %url, "Sending LLM request");

    let mut headers = reqwest::header::HeaderMap::new();
    headers.insert(
        reqwest::header::AUTHORIZATION,
        format!("Bearer {}", api_key)
            .parse()
            .map_err(|_| Error::Node("Invalid OpenAI API key format".to_string()))?,
    );
    headers.insert(
        reqwest::header::CONTENT_TYPE,
        HeaderValue::from_static("application/json"),
    );

    let mut messages = Vec::new();
    if let Some(sys) = system {
        messages.push(json!({"role": "system", "content": sys}));
    }
    messages.push(json!({"role": "user", "content": user}));

    let mut body = json!({
        "model": model,
        "messages": messages,
    });

    if let Some(temp) = config.temperature {
        body["temperature"] = json!(temp);
    }
    if let Some(max_tok) = config.max_tokens {
        body["max_tokens"] = json!(max_tok);
    }

    let response = client
        .post(&url)
        .headers(headers)
        .json(&body)
        .timeout(Duration::from_secs(config.timeout_seconds))
        .send()
        .await?;

    let status = response.status();
    debug!(provider = "openai", status = %status, "Received LLM response");
    let json: serde_json::Value = response.json().await?;

    if !status.is_success() {
        let msg = json["error"]["message"]
            .as_str()
            .unwrap_or("Unknown OpenAI error");
        return Err(Error::Node(format!(
            "OpenAI API error ({}): {}",
            status, msg
        )));
    }

    let content = json["choices"][0]["message"]["content"]
        .as_str()
        .ok_or_else(|| {
            Error::Node("Could not extract content from OpenAI response".to_string())
        })?
        .to_string();

    let returned_model = json["model"]
        .as_str()
        .unwrap_or(&model)
        .to_string();

    let usage = if json.get("usage").is_some() {
        Some(LlmUsage {
            prompt_tokens: json["usage"]["prompt_tokens"].as_u64(),
            completion_tokens: json["usage"]["completion_tokens"].as_u64(),
        })
    } else {
        None
    };

    Ok(LlmResponse {
        content,
        model: returned_model,
        usage,
    })
}

async fn call_anthropic(
    client: &Client,
    config: &LlmConfig,
    system: Option<&str>,
    user: &str,
) -> Result<LlmResponse> {
    let api_key = config.api_key.as_deref().ok_or_else(|| {
        Error::Node("Anthropic API key is required. Set `api_key` in LlmConfig.".to_string())
    })?;

    let url = resolve_endpoint(config);
    let model = config
        .model
        .clone()
        .unwrap_or_else(|| "claude-3-haiku-20240307".to_string());

    debug!(provider = "anthropic", model = %model, url = %url, "Sending LLM request");

    let mut headers = reqwest::header::HeaderMap::new();
    headers.insert(
        "x-api-key",
        api_key
            .parse()
            .map_err(|_| Error::Node("Invalid Anthropic API key format".to_string()))?,
    );
    headers.insert(
        "anthropic-version",
        HeaderValue::from_static("2023-06-01"),
    );
    headers.insert(
        reqwest::header::CONTENT_TYPE,
        HeaderValue::from_static("application/json"),
    );

    let max_tokens = config.max_tokens.unwrap_or(4096);

    let mut body = json!({
        "model": model,
        "max_tokens": max_tokens,
        "messages": [
            {"role": "user", "content": user}
        ],
    });

    if let Some(sys) = system {
        body["system"] = json!(sys);
    }
    if let Some(temp) = config.temperature {
        body["temperature"] = json!(temp);
    }

    let response = client
        .post(&url)
        .headers(headers)
        .json(&body)
        .timeout(Duration::from_secs(config.timeout_seconds))
        .send()
        .await?;

    let status = response.status();
    debug!(provider = "anthropic", status = %status, "Received LLM response");
    let json: serde_json::Value = response.json().await?;

    if !status.is_success() {
        let msg = json["error"]["message"]
            .as_str()
            .unwrap_or("Unknown Anthropic error");
        return Err(Error::Node(format!(
            "Anthropic API error ({}): {}",
            status, msg
        )));
    }

    let content = json["content"][0]["text"]
        .as_str()
        .ok_or_else(|| {
            Error::Node("Could not extract content from Anthropic response".to_string())
        })?
        .to_string();

    let returned_model = json["model"]
        .as_str()
        .unwrap_or(&model)
        .to_string();

    let usage = if json.get("usage").is_some() {
        Some(LlmUsage {
            prompt_tokens: json["usage"]["input_tokens"].as_u64(),
            completion_tokens: json["usage"]["output_tokens"].as_u64(),
        })
    } else {
        None
    };

    Ok(LlmResponse {
        content,
        model: returned_model,
        usage,
    })
}

async fn call_ollama(
    client: &Client,
    config: &LlmConfig,
    system: Option<&str>,
    user: &str,
) -> Result<LlmResponse> {
    let url = resolve_endpoint(config);

    let model = config
        .model
        .clone()
        .unwrap_or_else(|| "llama3".to_string());

    debug!(provider = "ollama", model = %model, url = %url, "Sending LLM request");

    let mut messages = Vec::new();
    if let Some(sys) = system {
        messages.push(json!({"role": "system", "content": sys}));
    }
    messages.push(json!({"role": "user", "content": user}));

    let mut body = json!({
        "model": model,
        "messages": messages,
        "stream": false,
    });

    if let Some(temp) = config.temperature {
        body["options"] = json!({"temperature": temp});
    }

    let response = client
        .post(&url)
        .json(&body)
        .timeout(Duration::from_secs(config.timeout_seconds))
        .send()
        .await?;

    let status = response.status();
    debug!(provider = "ollama", status = %status, "Received LLM response");
    let json: serde_json::Value = response.json().await?;

    if !status.is_success() {
        let msg = json["error"].as_str().unwrap_or("Unknown Ollama error");
        return Err(Error::Node(format!(
            "Ollama API error ({}): {}",
            status, msg
        )));
    }

    let content = json["message"]["content"]
        .as_str()
        .ok_or_else(|| {
            Error::Node("Could not extract content from Ollama response".to_string())
        })?
        .to_string();

    // Ollama echoes the model name in the response; fall back to the config value.
    let returned_model = json["model"]
        .as_str()
        .unwrap_or(&model)
        .to_string();

    let usage = if json.get("prompt_eval_count").is_some() {
        Some(LlmUsage {
            prompt_tokens: json["prompt_eval_count"].as_u64(),
            completion_tokens: json["eval_count"].as_u64(),
        })
    } else {
        None
    };

    Ok(LlmResponse {
        content,
        model: returned_model,
        usage,
    })
}
